language: generic
sudo: false
before_script:
  - git clone https://git.savannah.gnu.org/git/gforth.git
  - cd gforth && ./autogen.sh && ./configure && make
script: ~/gforth/gforth -m22M khakas/test.fs
