language: generic
sudo: false
apt:
  sources:
  - deb http://archive.ubuntu.com/ubuntu/ trusty universe
  packages:
  - gforth
#before_script:
#  - git clone https://git.savannah.gnu.org/git/gforth.git
#  - cd gforth && ./autogen.sh && ./configure && make
script: gforth -m22M khakas/test.fs
