dist: bionic
language: generic
sudo: true
before_script:
  - sudo apt-get install gforth || true
  # - git clone https://git.savannah.gnu.org/git/gforth.git
  # - (cd gforth && ./install-deps.sh && ./autogen.sh && ./configure --enable-lib && make && sudo make install)
script: gforth -m22M khakas/test.fs
