T{ S" абылағ+ы" S" абылаа" parse-test -> TRUE }T
\ искл? T{ S" ағ+ы" S" аа" parse-test -> FALSE }T
T{ S" ағ+ы" S" ағы" parse-test -> TRUE }T
T{ S" аң+ы" S" аңы" parse-test -> TRUE }T
T{ S" аң+ы" S" аа" parse-test -> FALSE }T
T{ S" ізік+ім" S" ізиим" parse-test -> TRUE }T
T{ S" ізік+ім" S" ізігім" parse-test -> TRUE }T
T{ S" киме+ге" S" кимее" parse-test -> TRUE }T
T{ S" кізі+ге" S" кізее" parse-test -> TRUE }T
T{ S" кӧг+і" S" кӧӧ" parse-test -> TRUE }T
T{ S" кӧзӧ+ге" S" кӧзӧге" parse-test -> TRUE }T
T{ S" маң+ы" S" маа" parse-test -> TRUE }T
T{ S" марығ+ы" S" марии" parse-test -> TRUE }T
T{ S" марығ+ы" S" марығы" parse-test -> FALSE }T
T{ S" мағаа+ох" S" мағааох" parse-test -> TRUE }T
T{ S" нуғ+ар" S" нуур" parse-test -> TRUE }T
T{ S" ӧң+і" S" ӧӧ" parse-test -> TRUE }T
T{ S" пағ+ы" S" паа" parse-test -> TRUE }T
T{ S" пар+и+ған" S" париған" parse-test -> TRUE }T
T{ S" пӧрік+ім" S" пӧриим" parse-test -> TRUE }T
T{ S" пуғ+ы" S" пуу" parse-test -> TRUE }T
T{ S" пу+ох" S" пуох" parse-test -> TRUE }T
T{ S" пызо+ға" S" пызоға" parse-test -> TRUE }T
T{ S" сағ+ы" S" саа" parse-test -> TRUE }T
T{ S" салаа+ға" S" салааға" parse-test -> TRUE }T
T{ S" сана+ар" S" санир" parse-test -> TRUE }T
T{ S" сап+ып" S" саап" parse-test -> TRUE }T
T{ S" сиг+ер" S" сиир" parse-test -> TRUE }T
T{ S" сиг+і" S" сии" parse-test -> TRUE }T
T{ S" сиг+іп" S" сиип" parse-test -> TRUE }T
T{ S" сине+еңер" S" синееңер" parse-test -> TRUE }T
T{ S" сине+елер" S" синеелер" parse-test -> TRUE }T
T{ S" сине+ибіс" S" синибіс" parse-test -> TRUE }T
T{ S" сине+им" S" синим" parse-test -> TRUE }T
T{ S" сіліг+і" S" сілии" parse-test -> TRUE }T
T{ S" соғ+ар" S" соор" parse-test -> TRUE }T
T{ S" соғ+ы" S" соғы" parse-test -> TRUE }T
T{ S" суғ+ға" S" суға" parse-test -> TRUE }T
T{ S" суғ+ы" S" суу" parse-test -> TRUE }T
T{ S" сӱрдег+і" S" сӱрдее" parse-test -> TRUE }T
T{ S" сурығ+ы" S" сурии" parse-test -> TRUE }T
T{ S" тағ+ы" S" таа" parse-test -> TRUE }T
T{ S" тап+ып" S" таап" parse-test -> TRUE }T
T{ S" таста+aр+ғa" S" тастирға" parse-test -> TRUE }T
T{ S" теп+іп" S" тееп" parse-test -> TRUE }T
T{ S" тоң+ар" S" тоор" parse-test -> TRUE }T
T{ S" тоң+ып" S" тооп" parse-test -> TRUE }T
T{ S" тӱк+і" S" тӱгі" parse-test -> TRUE }T
T{ S" тӱлгӱ+ге" S" тӱлгее" parse-test -> TRUE }T
T{ S" тура+ға" S" тураа" parse-test -> TRUE }T
T{ S" ӱг+ер" S" ӱӱр" parse-test -> TRUE }T
T{ S" узу+аң" S" узааң" parse-test -> TRUE }T
T{ S" узу+ар" S" узир" parse-test -> TRUE }T
T{ S" уйғу+ға" S" уйғаа" parse-test -> TRUE }T
T{ S" улуғ+ы" S" улии" parse-test -> TRUE }T
\ T{ S" хан-пиг+і" S" хан-пигі" parse-test -> TRUE }T
T{ S" харах+ым" S" хараам" parse-test -> TRUE }T
T{ S" хах+ы" S" хағы" parse-test -> TRUE }T
T{ S" хузух+ым" S" хузиим" parse-test -> TRUE }T
T{ S" хус+тар" S" хустар" parse-test -> TRUE }T
T{ S" чазы+ға" S" чазаа" parse-test -> TRUE }T
T{ S" чайлағ+ы" S" чайлаа" parse-test -> TRUE }T
T{ S" чиң+ер" S" чиңер" parse-test -> TRUE }T
T{ S" чиң+іп" S" чиип" parse-test -> TRUE }T
T{ S" чілің+і" S" чілии" parse-test -> TRUE }T
T{ S" чӧгіг+і" S" чӧгии" parse-test -> TRUE }T
T{ S" чӧлег+і" S" чӧлее" parse-test -> TRUE }T
T{ S" чӧлег+ім" S" чӧлеем" parse-test -> TRUE }T
T{ S" чӱг+і" S" чӱгі" parse-test -> TRUE }T
T{ S" чӱзӱг+і" S" чӱзии" parse-test -> TRUE }T
T{ S" чӱк+і" S" чӱгі" parse-test -> TRUE }T
T{ S" чух+ы" S" чуғы" parse-test -> TRUE }T
T{ S" чығ+а" S" чыға" parse-test -> TRUE }T
T{ S" чығ+адыр" S" чығадыр" parse-test -> TRUE }T
T{ S" чығ+ар" S" чыыр" parse-test -> TRUE }T
T{ S" чығ+ып" S" чыып" parse-test -> TRUE }T
T{ S" ырла+ибыс" S" ырлибыс" parse-test -> TRUE }T
T{ S" ырла+им" S" ырлим" parse-test -> TRUE }T
T{ S" эг+гей" S" эгей" parse-test -> TRUE }T
T{ S" эг+ер" S" ээр" parse-test -> TRUE }T
